Sinatra
wozane/app_wozane pull request #15
Opened 2017-07-10 11:24 UTC by wozane

2017-07-10 11:25 UTC, wozane commented
@esse request for review

2017-07-11 08:11 UTC, esse requested changes
Final touch

2017-07-11 08:11 UTC, esse commented on spec/test_authenticator.rb
> +    assert_equal(true, Authenticator.authenticate?('foo', 'bar'))
it's better to use simply `assert Authenticator.authenticate?('foo', 'bar')`, it's equivalent

2017-07-11 08:11 UTC, esse commented on spec/test_authenticator.rb
> +    assert_equal(false, Authenticator.authenticate?('foo', 'poo'))
it's better to use simply `assert !Authenticator.authenticate?('foo', 'poo')`, it's equivalent

2017-07-11 08:11 UTC, esse commented on wozane.rb
> +    erb :admin
I would love to see here authentication check ;)

2017-07-11 08:14 UTC, wozane commented on spec/test_authenticator.rb
> +    assert_equal(false, Authenticator.authenticate?('foo', 'poo'))
👍

2017-07-11 08:15 UTC, wozane commented on spec/test_authenticator.rb
> +    assert_equal(true, Authenticator.authenticate?('foo', 'bar'))
👍

2017-07-11 08:45 UTC, wozane commented on wozane.rb
> +    erb :admin
@esse please check if this can work

2017-07-11 08:47 UTC, esse approved these changes

2017-07-11 08:56 UTC, merged